name: CI/CD - Petlog Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.actor }}/pet-log-frontend
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: self-hosted
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply frontend manifests
        run: |
          DEPLOY_NAME=$(yq -r '.metadata.name' deploy/deployment.yaml)
          kubectl apply -n petlog -f deploy/deployment.yaml
          kubectl apply -n petlog -f deploy/service.yaml
          kubectl apply -n petlog -f deploy/ingress.yaml
          kubectl rollout restart deployment -n petlog $DEPLOY_NAME
